config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games do
    resources :comments
    resources :screenshots
  end
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :rating, presence: true
  validates :content, presence: true
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
    validates :title, presence: true
    validates :image, presence: true
    mount_uploader :image, BoxArtUploader
    has_many :comments
    has_many :screenshots
    # accepts_nested_attributes_for :screenshots

    def self.search(search)
        where("title LIKE ?", "%#{search}%") # the 'where' statement handles the rest of the syntax for a SQL query here
    end
end

app/models/screenshot.rb
class Screenshot < ApplicationRecord
    validates :image, presence: true
    mount_uploader :image, ScreenshotUploader
    belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_game
    before_action :find_comment, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    def create
        @comment = @game.comments.create(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            get_average
            @game.rating = @average_rating
            @game.save
            
            redirect_to game_path(@game)
        else
            redirect_to game_path(@game)
        end

    end

    def edit # possible that this may stay blank?
        @comment = @game.comments.find(params[:id])
    end

    def update
        if @comment.update(comment_params)
            get_average
            @game.rating = @average_rating
            @game.save
             
            redirect_to game_path(@game)
        else
            render 'edit'
        end

    end

    def destroy
        if @comment.destroy
            get_average
            @game.rating = @average_rating
            @game.save

        end

        redirect_to game_path(@game)
    end

    private

    def comment_params
        params.require(:comment).permit(:rating, :content)
    end
    
    def find_game
        @game = Game.find(params[:game_id])
    end

    def find_comment
        @comment = @game.comments.find(params[:id])
    end

    def get_average
        @sum = 0
        for comment in @game.comments
            @sum += comment.rating
        end

        if @game.comments.count > 1
            @average_rating = @sum / (@game.comments.count)
        else
            @average_rating = @sum
        end
        
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :find_game, only: [:show, :update, :edit, :destroy]

    def index
        # show all games unless a search parameter is recieved, if one is then show results
        @games = Game.all
        if params[:search]
            @games = Game.search(params[:search]).order("created_at DESC")
        else 
            @games = Game.all.order("created_at DESC")
        end

    end

    def show
        find_game
    end

    def new
        @game = Game.new
    end

    def create
        @game = Game.new(game_params)
        if @game.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @game.update(game_params)
            redirect_to game_path
        else 
            render 'edit'
        end
    end

    def destroy
        @game.destroy
        redirect_to root_path
    end

    private
        def game_params
            params.require(:game).permit(:title, :image, :description, :rating)
        end
        
        def find_game
            @game = Game.find(params[:id])
        end

end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
    before_action :find_game
    before_action :find_screenshot, only: [:edit, :update, :destroy]

    def index
        @screenshots = @game.screenshots.all.order("created_at DESC")
    end

    def create
        @screenshot = @game.screenshots.create(screenshot_params)
        if @screenshot.save
            redirect_to game_path(@game)
        else
            redirect_to game_path(@game)
        end

    end

    def destroy
        @screenshot.destroy
        redirect_to game_path(@game)
    end

    private

    def screenshot_params
        params.require(:screenshot).permit(:title, :image)
    end
    
    def find_game
        @game = Game.find(params[:game_id])
    end

    def find_screenshot
        @screenshot = @game.screenshots.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" } [flash_type] || flash_type.to_s
    end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
                end)
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/views/comments/_comment.html.erb
<div class="review">
    <div class="comment-rating" data-score="<%= comment.rating %>"></div>
    <p>Posted by: <%= comment.user.username %> <%= time_ago_in_words(comment.created_at) %> ago.</p>
    <p class="review-comment"><%= comment.content %></p>

    <div class="links">
        <% if user_signed_in? %>
            <% if comment.user_id == current_user.id %>
                <div class="links btn-group">
                    <%= link_to "Edit", edit_game_comment_path(comment.game, comment),
                        class: "btn btn-custom" %>
                    <%= link_to "Delete", game_comment_path(comment.game, comment),
                        method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@game, @game.comments.build]) do |f| %>
    <div id="rating-form">
        <label> Rating </label>
    </div>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit, "Add Review" %>
<% end %>

<script src="../../assets/javascripts/jquery.raty.js"></script>
<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'comment[rating]'
});
</script>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@game, @comment]) do |f| %>
    <div id="rating-form">
        <label> Rating </label>
    </div>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit %>
<% end %>

<script src="../../assets/javascripts/jquery.raty.js"></script>
<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'comment[rating]'
});
</script>

app/views/games/_form.html.erb
<div class="new-game-form">
  <%= simple_form_for @game do |f| %>
    <%= f.input :title, label: "Game Title" %>
    <%= f.input :description, label: "Description" %>
    <%= f.label :box_art, "Box Art" %>
    <%= f.file_field :image %><br>
    <%= f.button :submit, class: "btn btn-custom" %>
  <% end %>
</div>

app/views/games/_screenshots.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @game.screenshots.each_with_index do |screenshot, i| %>
        <li data-target="#myCarousel" data-slide-to="<%= i %>" class="<% if i == 0 %>active<% end %>"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner screenshot">
      <div class="item active">
        <%= image_tag @game.screenshots.first.image.url %>
      </div>
      <% @game.screenshots.drop(1).each do |screenshot| %>
        <div class="item">
          <%= image_tag screenshot.image.url %>
        </div>
      <% end %>
    </div>

  <!-- Left and right controls -->
  <a class="left carousel-control screenshot-arrows" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control screenshot-arrows" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/games/edit.html.erb
<h1>Edit Game</h1>
<%= render 'form' %>

app/views/games/index.html.erb
<div class="row">
    <% if @games.count != 0 %>
        <% @games.each do |game| %>
            <div class="col-md-3">
                <a href="/games/<%= game.id %>">
                    <%= image_tag game.image.url, class: "game" %>
                </a>
            </div>
        <% end %>
    <% else %>
        <% if !params[:search].blank? %>
            <h4>No games were found matching <%= params[:search] %>.</h4>
        <% else %>
            <h1 class="col-md-8 col-md-offset-4">No Games Yet!</h1>
        <% end %>
    <% end %>
</div>

<script src="../../assets/javascripts/jquery.raty.js"></script>
<script>
    $('.comment-rating').raty({
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

app/views/games/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <h1>Add a Game</h1>
    <%= render 'form' %>
</div>

app/views/games/show.html.erb
<div class="row">
    <div class="col-md-4">
        <%= image_tag @game.image.url, class: "game-show" %>
        <div class="text-center">
            <div class="links btn-group">
                <% if user_signed_in? %>
                    <%= link_to "Edit", edit_game_path(@game), class: "btn btn-custom" %>
                    <%= link_to "Delete", game_path(@game), method: :delete,
                        data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="game-info">
            <h1 class="game-title"><%= @game.title %></h1>
            <h4 class="avg-rating">Average Rating</h4>
            <div class="comment-rating" data-score="<%= @game.rating %>"></div>
            <span class="number-of-reviews">(Based on <%= @game.comments.count %> reviews)</span><br>
            <p class="game-desc"><%= @game.description %></p>
            <div class="screenshots">
                <h2 class="text-center">Screenshots</h2>
                    <% if @game.screenshots.count > 0 %>
                        <a href="/games/<%= @game.id %>/screenshots">
                            <%= render 'screenshots' %>
                        </a>
                    <% else %>
                        <p class="text-center">No screenshots yet!</p>
                    <% end %> 
                <div class="text-center">
                    <% if user_signed_in? %>
                        <%= link_to new_game_screenshot_path(@game), class: "btn btn-custom" do %>
                            <i class="glyphicon glyphicon-plus"></i>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="reviews">
            <% if @game.comments.count == 0 %>
                <h1>No Reviews Yet!</h1>
            <% else %>
                <h1>Reviews:</h1>
                <%= render @game.comments %>
            <% end %>

            <h4>Review this Game!</h4>
                <%= render 'comments/form' %>
                
        </div>
    </div>
</div>

<!-- Raty JQuery Script -->
<script src="../../assets/javascripts/jquery.raty.js"></script>
<script>
    $('.comment-rating').raty({
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Reviewer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to  "Games", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <div class="col-sm-3 col-md-3 pull-right">
          <%= form_tag games_path, method: "get", class: "navbar-form", role: "search" do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], size: 150, placeholder: "Search Games", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag type: "submit", class: "btn btn-custom-navbar", :name => nil do %>
                    <i class="glyphicon glyphicon-search"></i>
                  <% end %>
                </div>
            </div>
          <% end %>
        </div>

        <% if user_signed_in? %>
          <p><%= link_to "New Game", new_game_path, class: "navbar-right navbar-text navbar-link" %></p>
        <% end %>

      </div>
    </div>

    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/screenshots/index.html.erb
<h1>Screenshots: 
    <a href="/games/<%= @game.id %>">
        <%= @game.title %>
    </a>
</h1>

<% if @screenshots.count > 0 %>
    <% @screenshots.each do |screenshot| %>
        <div class="screenshot-border">
            <div class="pull-left">
                <h3><%= screenshot.title %></h3>
            </div>
            <%= image_tag screenshot.image.url, class: "screenshot-show" %>
            <% if user_signed_in? %>
                <%= link_to game_screenshot_path(screenshot.game, screenshot), method: :delete,
                    data: { confirm: "Are you sure?" }, class: "btn btn-custom3" do %>
                        <i class="glyphicon glyphicon-trash"></i>
                    <% end %>
            <% end %>
        </div>
    <% end %>
<% else %>
    <h2>No Screenshots Yet!</h2>
<% end %>

app/views/screenshots/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="new-game-form">
        <h1>Add Some Screenshots</h1>
        <%= simple_form_for([@game, @game.screenshots.build]) do |f| %>
            <%= f.input :title %>
            <%= f.label :screenshots %>
            <%= f.file_field :image %><br>
            <%= f.button :submit, "Add Screenshot", class: "btn btn-custom"  %>
        <% end %>
    </div>
</div>